services:
  sk-service:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    working_dir: /app
    volumes:
      - ./sk-service:/app
    command: ["dotnet", "sk-service.dll"]
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  backend:
    image: node:20
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/frontend/dist:ro
    command: ["node", "server.js"]
    environment:
      SERVICE_URL: http://sk-service:5000
    ports:
      - "8123:2024"
